[module "src/common_cpp"]
	path = src/common_cpp
	url = https://github.com/servo-robot-520/common_cpp.git
	branch = main
[module "src/servo_robot_board_interface"]
	path = src/servo_robot_board_interface
	url = https://github.com/servo-robot-520/servo_robot_board_interface.git
	branch = main
[module "src/servo_robot_board_bridge"]
	path = src/servo_robot_board_bridge
	url = https://github.com/servo-robot-520/servo_robot_board_bridge.git
	branch = main
[module "src/ydlidar_ros2_driver"]
	path = src/ydlidar_ros2_driver
	url = https://github.com/servo-robot-520/ydlidar_ros2_driver.git
	branch = humble
