<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
        schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>hexapod_ros2_bringup</name>
    <version>0.1.0</version>
    <description>Integration launch files and configs for the hexapod</description>
    <maintainer email="ohmdmbct@gmail.com">zwh</maintainer>
    <license>GPL-3.0</license>

    <exec_depend>camera_node</exec_depend>
    <exec_depend>servo_robot_board_interface</exec_depend>
    <exec_depend>servo_robot_board_bridge</exec_depend>
    <exec_depend>ydlidar_ros2_driver</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
